### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by goofballLogic** [michaelmitchell/c9.ide.language.javascript.eslintd#1]
thanks for building this a great help. Can you add a way to patreon/opencollective or something similar?

**Comment by michaelmitchell** [comment]
Thanks for the kind words, I set up [liberapay](https://liberapay.com/michaelmitchell) if you would like to make a contribution.

Someone let me know when this stops being awesome so I can resolve the issue :)

**Comment by goofballLogic** [comment]
Just making a 1 time payment (cancelling after first occurrance). 

Would help if you could add notes on how to see log messages. Am seeing it work for a while then stop but don't know how to see what errors it might be experiencing.

⁣Sent from TypeApp ​

**Comment by michaelmitchell** [comment]
You should see any errors in the browser console for Cloud9 (chrome devtools etc..), if its linting you will see messages about the time it took and how many messages it found as you edit.

Post any errors in new issues along with the source code for the file causing the errors where possible, I've only just started using this full time for myself so there is no doubt going to be a few things to sort out but I can fix them quickly once I know what they are.
